//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rentalBackEnd_Web_API.EntityModel
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class Rental
    {

        public int Rental_ID { get; set; }
        public int User_ID { get; set; }
        public int Vehicle_ID { get; set; }
        public System.DateTime Start_Date { get; set; }
        public System.DateTime Return_Date { get; set; }
        public Nullable<System.DateTime> Returned_Date { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
    }
}
