//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rentalBackEnd_Web_API.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Rentals_DB_BusinessEntities : DbContext
    {
        public Rentals_DB_BusinessEntities()
            : base("name=Rentals_DB_BusinessEntities")
        {

        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Vehicle_Makes> Vehicle_Makes { get; set; }
        public virtual DbSet<Vehicle_Models> Vehicle_Models { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Coordinate> Coordinates { get; set; }
        public virtual DbSet<Rental> Rentals { get; set; }
        public virtual DbSet<Vehicle_Types> Vehicle_Types { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
    }
}
