//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rentalBackEnd_Web_API.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle_Types
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle_Types()
        {
            this.Vehicles = new HashSet<Vehicle>();
        }
    
        public int Vehicle_Type_ID { get; set; }
        public int Make_ID { get; set; }
        public int Model_ID { get; set; }
        public int Daily_Rate { get; set; }
        public int Penalty_Rate { get; set; }
        public int Year { get; set; }
        public string Gear_Type { get; set; }
    
        public virtual Vehicle_Makes Vehicle_Makes { get; set; }
        public virtual Vehicle_Models Vehicle_Models { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicle> Vehicles { get; set; }
    }
}
