// <auto-generated />
namespace rentalBackEnd_Web_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class BaseDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BaseDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201802241317340_BaseDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
